apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins-docker
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: task3-minikube-container
        image: grobkardev/jenkins-docker-task:latest
        ports:
        - containerPort: 80
